version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mps-lambda-proxy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1glfdsfwi55v5"
s3_prefix = "mps-lambda-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
