AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mps-lambda-proxy

  SAM Template for mps-lambda-proxy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters: 
  EnvironmentType: 
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues: 
      - prod
      - dev
    ConstraintDescription: must be a prod or dev

Mappings:
  Environment:
    dev:
      SecurityGroupId:
        - sg-05fa1e172b3da9115
      Subnets:
        - subnet-00b9cffed05f69a59
        - subnet-76532401
        - subnet-e176cbca
    prod:
      SecurityGroupId:
        - sg-06aa30866f9360af9
      Subnets:
        - subnet-6440273d
        - subnet-275a1950

Resources:
  MpsProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: proxy/
      Handler: proxy.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
            AllowOrigins:
              - "*"
            AllowCredentials: false
            AllowMethods:
              - GET
              - POST
            AllowHeaders:
              - x-amzn-header
              - authorization
              - content-type
            ExposeHeaders:
              - date
              - content-type
            MaxAge: 30
      Policies:
        - Statement:
          - Sid: AllowVPCAttachment
            Effect: Allow
            Action:
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Resource: '*'
      VpcConfig:
        SecurityGroupIds: !FindInMap [Environment, !Ref EnvironmentType, SecurityGroupId]
        SubnetIds: !FindInMap [Environment, !Ref EnvironmentType, Subnets]


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MpsProxyFunction:
    Description: "Proxy Lambda Function ARN"
    Value: !GetAtt MpsProxyFunction.Arn
  MpsProxyFunctionIamRole:
    Description: "Implicit IAM Role created for MPS Proxy function"
    Value: !GetAtt MpsProxyFunctionRole.Arn
  MpsProxyFunctionUrlEndpoint:
      Description: "MPS Proxy Function URL Endpoint"
      Value:
        Fn::GetAtt: MpsProxyFunctionUrl.FunctionUrl
